name: SlackNotification

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: adeelraza/kalsym
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          #tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kalsym:2.2
          tags: ${{ steps.meta.outputs.tags }}
      - 
        name: Slack Notify
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_CHANNEL: devops-training
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Your Status of the Workflow is  ${{ job.status }}'
          SLACK_TITLE: Workflow Status
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
